# version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=sems.settings
    depends_on:
      - db
  
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: sgetme
      MYSQL_PASSWORD: sgetme
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Mengist#2451
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
     - 33066:3306

