# Generated by Django 5.0.6 on 2025-03-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
    ]
