# Generated by Django 5.0.6 on 2025-03-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_password_user_password_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='department_name',
        ),
    ]
