# Generated by Django 5.0.6 on 2025-03-30 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chair_course_department_faculty_role_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='modules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_modules', to='api.module'),
        ),
        migrations.AlterField(
            model_name='department',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_questions', to='api.question'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_tests', to='api.test'),
        ),
    ]
