# Generated by Django 5.0.6 on 2025-03-30 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_course_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='api.course'),
        ),
    ]
