# Generated by Django 5.0.6 on 2025-03-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_module_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='api.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.course'),
        ),
    ]
