# Generated by Django 5.0.6 on 2025-03-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_course_module_alter_module_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='module',
        ),
    ]
