# Generated by Django 5.0.6 on 2025-03-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_course_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
    ]
