# Generated by Django 5.0.6 on 2025-03-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_module_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='api.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department'),
        ),
    ]
