# Generated by Django 5.0.6 on 2025-03-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_test_department_test_responses_test_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='department',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tests',
        ),
    ]
