# Generated by Django 5.0.6 on 2025-03-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_department_modules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='courses',
        ),
    ]
